### ISSUE TITLE
Install issue: missing gridgen input file

### ISSUE THREAD

**Issue by GengXia-NREL** [NOAA-EMC/gridgen#9]
Dear developers

I am trying to install gridgen following your instructions. However i think the input file (gridgen_addit.tgz) is no longer available at polar.ncep.noaa.gov/tempor/ww3ftp. I would appreciate if anyone can provide me with the most updated file link.  Thanks in advance

Sincerely
Geng Xia

**Comment by GengXia-NREL** [comment]
Hi Ali

Thanks for the help.

Sincerely
Geng Xia

Ali.Abdolali ***@***.***> 于2023年3月6日周一 08:19写道：

**Comment by aliabdolali** [comment]
try this
https://drive.google.com/file/d/1AYPnsc1ZISrcGuyHMBKVWTFFgOQBjwE-/view?usp=share_link
you need to ask for permission and i will grant it.
